# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ute}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Denis Knauf"]
  s.date = %q{2013-01-20}
  s.description = %q{Many template engines in one collection with one universal API}
  s.email = %q{Denis.Knauf@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "README.md",
    "VERSION",
    "lib/templates.rb",
    "lib/templates/engine.rb",
    "lib/templates/engines/kramdown.rb"
  ]
  s.homepage = %q{https://github.com/DenisKnauf/ute}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Universal Template Engines Collection}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

